### ISSUE TITLE
[Newbie] How to write first post?

### ISSUE THREAD

**Issue by kubahaha** [lalcmellkmal/doushio#116]
Hi! I get Doushio up and running, now my question is: Did I broke something? Or it is supposed
 to look like this at first run?
![screenshot at 19-24-56](https://cloud.githubusercontent.com/assets/6720051/8189572/7694d666-145d-11e5-8183-0498b8950cca.png)
Can somebody provided guide how to get it working?

**Comment by underr** [comment]
You should set `SERVE_STATIC_FILES` to `true` at config.js

**Comment by kubahaha** [comment]
Thanks for reply, everything works fine now
