### ISSUE TITLE
Replacement for Persona

### ISSUE THREAD

**Issue by vampiricwulf** [lalcmellkmal/doushio#119]
Since it's going away soon.
I was looking at https://steamcommunity.com/dev with http://passportjs.org .
or something firefox recommends (https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers) is: https://passwordless.net/

**Comment by underr** [comment]
As I'm too lazy to implement it by myself, this would be great.

**Comment by vampiricwulf** [comment]
Persona is now officially dead. @lalcmellkmal

**Comment by brunoduran** [comment]
Portier might be an alternative, though it is still in beta:

https://portier.github.io/

**Comment by lalcmellkmal** [comment]
Well, I'm sorry for being so late. But I implemented GitHub OAuth in 8375fc5d46f65c0d795e34164e045bf13de355be
