### ISSUE TITLE
Typing on mobile is broken 

### ISSUE THREAD

**Issue by thestartofsomethingnew** [lalcmellkmal/doushio#122]
The letters are all fugged up when using any Android keyboard.

**Comment by lalcmellkmal** [comment]
Yeah, I need to borrow an Android phone to figure out why.

One thing worth trying is disabling Autocorrect in the options menu.

**Comment by thestartofsomethingnew** [comment]
Try using virtualbox with an Android iso.

**Comment by thestartofsomethingnew** [comment]
Btw is there a reason why meguca doesn't have this problem?

**Comment by lalcmellkmal** [comment]
they must have debugged it

**Comment by bakape** [comment]
Solution is simple: remove the autocomplete attribute on `#trans`. Let the browser decide, whether autocomplete  is needed.

**Comment by thestartofsomethingnew** [comment]
Could you spoon feed me through how to do that? What exactly i need to change?

**Comment by lalcmellkmal** [comment]
@bakape wait, wait, _remove_ the autocomplete attribute? and here i was thinking `autocomplete="off"` is what fixes this issue on Android

@thestartofsomethingnew i recently added an autocomplete option, so we could just tweak its default setting for Android.

**Comment by lalcmellkmal** [comment]
(thanks for the tip BTW, i didn't mean to be confrontational!)

**Comment by bakape** [comment]
@lalcmellkmal 
I think that is what fixed it, because the `autocomplete` attribute has very inconsistent implementations across both desktop and mobile platforms. I could be remembering wrong though. That was several years ago. 
No problem.

**Comment by thestartofsomethingnew** [comment]
@lalcmellkmal I've removed the code for autocomplete where you committed "disable autocomplete" but I'm still having the same problem. Would you be able to show me how to fully delete it? I might be doing it wrong.

@bakape Thanks again!

**Comment by lalcmellkmal** [comment]
@thestartofsomethingnew here, try this change where autocomplete=off by default

**Comment by thestartofsomethingnew** [comment]
@lalcmellkmal Auto-complete is unchecked but I think it's still on. I might be wrong. You can test it on my site.

**Comment by lalcmellkmal** [comment]
Oops. That's what I get for not testing my code properly.
