### ISSUE TITLE
Unbanning IPs

### ISSUE THREAD

**Issue by thestartofsomethingnew** [lalcmellkmal/doushio#123]
Is it possible to unban an ip or all ips after you've deleted their posts?

**Comment by lalcmellkmal** [comment]
I guess I never did implement that, eh? Hmm...

**Comment by thestartofsomethingnew** [comment]
Is it possible through redis somehow?

**Comment by lalcmellkmal** [comment]
whoops i didn't read your question very well

@thestartofsomethingnew yeah in redis you can modify the `hot:timeouts` set, then reload with `node server/kill.js`

you should also be able to view deleted posts by adding `#reported` to the URL, although I think this might actually not be working at the moment...

**Comment by thestartofsomethingnew** [comment]
So bans are on a timeout system? Ah I had no idea.
Thank you @lalcmellkmal
